/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activities guests can do in bookable areas
         * @description Activity tags with the number of bookable areas and published landmarks that have them, most areas first. Activities with no bookable area are left out.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description activities with counts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["activity"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Destinations with something to book
         * @description Areas with at least one active listing, most listings first, each with its top three activities (by how many published landmarks carry them).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description bookable areas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["area_card"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A destination: its landmarks and what to book there */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a province lists the areas under it that have something to book */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["area_detail"];
                    };
                };
                /** @description unknown area */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the API and its database answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            postgis: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/complete_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Finish sign-up with a name and phone
         * @description Sign-up asks only for email and password; the web app sends a user whose `registration_complete` is false here before anything else. Both fields are required. Guests and partners alike.
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        /** @description Digits, spaces, ( ) - and a leading +; 7 to 15 digits */
                        phone: string;
                    };
                };
            };
            responses: {
                /** @description a partner completes theirs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description phone with no digits */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in guest's profile
         * @description Guest-only (a partner's is /api/v1/partner/profile). Fields are null until the profile is first saved; `complete` drives the web app's banner.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a saved profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["guest_profile"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a partner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        /**
         * Save the signed-in guest's profile
         * @description Guest-only. Every field is required except `address.province`; `phone` is saved on the user. Email can't be changed here.
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        legal_first_name: string;
                        legal_last_name: string;
                        phone: string;
                        address: {
                            street: string;
                            city: string;
                            region: string;
                            /** @description Optional: none in Metro Manila */
                            province?: string | null;
                            postal_code: string;
                            /** @description ISO 3166-1 alpha-2, e.g. PH */
                            country: string;
                        };
                    };
                };
            };
            responses: {
                /** @description a display name and an email are ignored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["guest_profile"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a partner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a phone that isn't a phone number saves nothing */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user"];
                    };
                };
                /** @description an expired token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the signed-in user's profile
         * @description Only `name` and `phone`; keys left out are unchanged. A blank or null `phone` clears it.
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        phone?: string | null;
                    };
                };
            };
            responses: {
                /** @description a blank phone clears it */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description phone given as a number */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/partner/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in partner
         * @description Partner-only, like everything under /api/v1/partner.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the partner */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oauth/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in or sign up with Google or Facebook
         * @description `token` is a Google Identity Services ID token or a Facebook Login access token. It signs in to, links or creates an account of `role` only, so one Google account can have a guest and a partner account.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "google" | "facebook";
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        token: string;
                        /** @enum {string} */
                        role: "guest" | "partner";
                    };
                };
            };
            responses: {
                /** @description a new user is created with the entry point's role */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["auth_tokens"];
                    };
                };
                /** @description the provider rejects the token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description unknown provider */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description token missing */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
                /** @description too many attempts from one IP */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partner/listing_options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What a new listing can be: its bookable categories
         * @description Partner-only. Bookable (leaf) categories with the JSON Schema their `attrs` must match.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description leaf categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["listing_options"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partner/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in partner's listings
         * @description Partner-only. Every listing the partner owns, in any status, ordered by category name, then title. The exact location is included: the reader owns the listing.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description only the partner's own listings, by category then title */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["partner_listing"][];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add a listing
         * @description Partner-only. The listing is saved as a draft; any `status` sent is ignored. `attrs` is checked against the category's `attribute_schema` (see `GET /api/v1/partner/listing_options`). The listing's area is the city, town or island nearest the pin, within 50 km. The partner must have passed the ID check first (`/api/v1/partner/verification`); until then it is a 403.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string;
                        /** @description A bookable (leaf) category */
                        category_id: number;
                        address: {
                            street: string;
                            city: string;
                            region: string;
                            /** @description Optional: none in Metro Manila */
                            province?: string | null;
                            postal_code: string;
                            /** @description ISO 3166-1 alpha-2, e.g. PH */
                            country: string;
                        };
                        location: {
                            lat: number;
                            lng: number;
                        };
                        attrs?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description an address without a province */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["partner_listing"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description an address that isn't an object */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partner/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in partner's profile
         * @description Partner-only. Fields are null until the profile is first saved; `complete` drives the web app's banner.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a saved profile without a phone is not complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["partner_profile"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        /**
         * Save the signed-in partner's profile
         * @description Partner-only. Every field but `display_name` is required; `phone` is saved on the user. Email can't be changed here.
         */
        put: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        display_name?: string | null;
                        legal_first_name: string;
                        legal_last_name: string;
                        phone: string;
                        address: {
                            street: string;
                            city: string;
                            region: string;
                            /** @description Optional: none in Metro Manila */
                            province?: string | null;
                            postal_code: string;
                            /** @description ISO 3166-1 alpha-2, e.g. PH */
                            country: string;
                        };
                    };
                };
            };
            responses: {
                /** @description no province, as in Metro Manila; a blank one is stored as null */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["partner_profile"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a phone that isn't a phone number saves nothing */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partner/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The partner's ID check
         * @description Partner-only. Where the partner's Didit ID check stands. While it is pending, the API asks Didit for news first, so the status is current when the partner comes back from Didit's page.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description declined three times: waiting out the cooldown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["partner_verification"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Start or resume the partner's ID check
         * @description Partner-only. Returns the URL of Didit's hosted page, where the partner scans their ID and takes a selfie; Didit sends them back to the web app's `/partner/verify` after. An unfinished check is resumed rather than started again. After 3 declined checks the partner waits an hour from the last one (429), then gets 3 more tries.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description three tries again once the cooldown has passed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["partner_verification_start"];
                    };
                };
                /** @description signed out */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a guest */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a check Didit is still reviewing */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
                /** @description declined three times within the hour */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            /** Format: date-time */
                            retry_at: string;
                        };
                    };
                };
                /** @description Didit can't be reached */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description Didit isn't configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up with email and password
         * @description `role` is the entry point: `guest` from /login, `partner` from /partner/login. Admin accounts are never self-made. `name` and `phone` are optional; the account starts with `registration_complete: false` until PUT /api/v1/me/complete_profile.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email: string;
                        name?: string;
                        phone?: string;
                        password: string;
                        /** @enum {string} */
                        role: "guest" | "partner";
                    };
                };
            };
            responses: {
                /** @description a sign-up from /partner makes a partner */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["auth_tokens"];
                    };
                };
                /** @description email already taken by the same role, in any case */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
                /** @description too many attempts from one IP */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search destinations, landmarks, tags and listings
         * @description One search box over areas, published landmarks, tags (activities, features, themes) and active listings. Accent- and typo-tolerant, and matches each record's aliases. At most 5 results per group. Areas without anything to book are left out, and listings carry no location.
         */
        get: {
            parameters: {
                query: {
                    /** @description At least 2 characters */
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description exact name ranks first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["search_results"];
                    };
                };
                /** @description query missing */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description `role` is the entry point signed in from. Email is unique per role, so only that role's account is looked up; an account of another role is not found (401).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                        /** @enum {string} */
                        role: "guest" | "partner" | "admin";
                    };
                };
            };
            responses: {
                /** @description signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["auth_tokens"];
                    };
                };
                /** @description an account made with Google has no password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description unknown role */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
                /** @description too many attempts from one IP */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        /** Sign out (revoke a refresh token) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description an unknown token is ignored */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description token missing */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trade a refresh token for new tokens
         * @description Each refresh token works once. Reusing one revokes every session of that user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description new tokens; the old refresh token is spent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["auth_tokens"];
                    };
                };
                /** @description an unknown token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description token given as an array */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["validation_errors"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/didit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Didit reports a change to an ID check
         * @description Called by Didit, not by the apps. Signed with HMAC-SHA256 of the raw body (`X-Signature`, keyed with the destination's secret) and timestamped (`X-Timestamp`, Unix seconds, at most 5 minutes off). The status in the body is not trusted: the API reads it back from Didit.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Signature"?: string;
                    "X-Timestamp"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        webhook_type?: string;
                        session_id: string;
                        status?: string;
                    };
                };
            };
            responses: {
                /** @description a check we don't know (an older session): ignored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description no signature */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Didit can't be asked for the status: Didit retries the delivery */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description no webhook secret configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        user: {
            id: number;
            email: string;
            name: string | null;
            phone: string | null;
            /** @enum {string} */
            role: "guest" | "partner" | "admin";
            /** @description False until name and phone are set (PUT /api/v1/me/complete_profile) */
            registration_complete: boolean;
        };
        profile_address: {
            street: string | null;
            city: string | null;
            region: string | null;
            /** @description Null where there is none */
            province: string | null;
            postal_code: string | null;
            /** @description ISO 3166-1 alpha-2, e.g. PH */
            country: string | null;
        };
        partner_profile: {
            /** @description Shown to travellers; optional */
            display_name: string | null;
            legal_first_name: string | null;
            legal_last_name: string | null;
            phone: string | null;
            /** @description Read-only here */
            email: string;
            address: components["schemas"]["profile_address"];
            /** @description True once the profile is saved and a phone is set */
            complete: boolean;
        };
        partner_verification: {
            /** @enum {string} */
            status: "not_started" | "in_progress" | "in_review" | "approved" | "declined" | "expired";
            /** Format: date-time */
            verified_at: string | null;
            /** @description Declined checks left before an hour's wait (3 at most) */
            attempts_left: number;
            /**
             * Format: date-time
             * @description Set while the partner must wait before starting another check
             */
            retry_at: string | null;
        };
        partner_verification_start: {
            /** @description Didit's hosted page; send the partner there */
            url: string;
            verification: components["schemas"]["partner_verification"];
        };
        guest_profile: {
            legal_first_name: string | null;
            legal_last_name: string | null;
            phone: string | null;
            /** @description Read-only here */
            email: string;
            address: components["schemas"]["profile_address"];
            /** @description True once the profile is saved and a phone is set */
            complete: boolean;
        };
        auth_tokens: {
            access_token: string;
            refresh_token: string;
            /** @description Seconds until the access token expires */
            expires_in: number;
            user: components["schemas"]["user"];
        };
        error: {
            error: string;
        };
        validation_errors: {
            errors: string[];
        };
        area_ref: {
            slug: string;
            name: string;
        };
        tag: {
            slug: string;
            name: string;
            /** @enum {string} */
            kind: "activity" | "feature" | "theme";
        };
        listing_summary: {
            id: number;
            title: string;
            category: string;
            area_slug: string;
        };
        partner_listing: {
            id: number;
            title: string;
            description: string;
            /** @enum {string} */
            status: "draft" | "pending" | "active";
            category: {
                id: number;
                slug: string;
                name: string;
                /** @enum {string} */
                booking_type: "rental" | "stay" | "activity" | "transfer";
            };
            area: components["schemas"]["area_ref"];
            address: components["schemas"]["profile_address"];
            location: {
                lat: number;
                lng: number;
            };
            /** @description Matches the category's attribute_schema */
            attrs: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        listing_options: {
            categories: {
                id: number;
                slug: string;
                name: string;
                /** @enum {string} */
                booking_type: "rental" | "stay" | "activity" | "transfer";
                parent_name: string | null;
                /** @description The JSON Schema a listing's attrs must match */
                attribute_schema: {
                    [key: string]: unknown;
                };
            }[];
        };
        area: {
            slug: string;
            name: string;
            /** @enum {string} */
            kind: "region" | "province" | "city" | "town" | "island";
            parent_name: string | null;
        };
        area_card: {
            slug: string;
            name: string;
            /** @enum {string} */
            kind: "region" | "province" | "city" | "town" | "island";
            parent_name: string | null;
            landmark_count: number;
            listing_count: number;
            activities: components["schemas"]["tag"][];
        };
        area_detail: {
            area: components["schemas"]["area"];
            /** @description Areas under this one that have something to book */
            areas: components["schemas"]["area"][];
            landmarks: {
                slug: string;
                name: string;
                description: string;
                tags: components["schemas"]["tag"][];
            }[];
            listings: {
                id: number;
                title: string;
                category: string;
                area_slug: string;
                /** @enum {string} */
                booking_type: "rental" | "stay" | "activity" | "transfer";
            }[];
        };
        activity: {
            slug: string;
            name: string;
            area_count: number;
            landmark_count: number;
        };
        search_results: {
            areas: {
                slug: string;
                name: string;
                /** @enum {string} */
                kind: "region" | "province" | "city" | "town" | "island";
                parent_name: string | null;
            }[];
            landmarks: {
                slug: string;
                name: string;
                area: components["schemas"]["area_ref"];
            }[];
            /** @description Matching tags, each with the bookable areas that have landmarks carrying it, most landmarks first */
            tags: {
                slug: string;
                name: string;
                /** @enum {string} */
                kind: "activity" | "feature" | "theme";
                areas: {
                    slug: string;
                    name: string;
                    landmark_count: number;
                }[];
            }[];
            listings: components["schemas"]["listing_summary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
