// Philippine address suggestions for the partner profile form (RAA-40): PSA regions,
// provinces and cities/municipalities, with GeoNames ZIP codes. data.json is generated by
// web/scripts/ph-address-data.mjs; it is loaded only when an address is in the Philippines.

export type Place = { code: string; name: string };
type City = Place & { province: string | null; region: string; zips: string[] };
export type PhAddressData = {
  source: { psgc: string; zip: string; built: string };
  regions: Place[];
  provinces: (Place & { region: string })[];
  cities: City[];
};

let loading: Promise<PhAddressData> | undefined;

export function loadPhAddressData() {
  loading ??= import("./data.json").then((module) => module.default as PhAddressData);
  return loading;
}

export function provincesOf(data: PhAddressData, regionCode: string | undefined) {
  return regionCode ? data.provinces.filter((p) => p.region === regionCode) : [];
}

// A region's cities under one province; Metro Manila has no provinces, and a few cities
// elsewhere sit outside one, so with no province it is the region's province-less cities.
export function citiesOf(data: PhAddressData, regionCode: string | undefined, provinceCode: string | undefined) {
  if (!regionCode) return [];
  return data.cities.filter((c) => c.region === regionCode && c.province === (provinceCode ?? null));
}

export function zipsOf(data: PhAddressData, cityCode: string | undefined) {
  return data.cities.find((c) => c.code === cityCode)?.zips ?? [];
}

// Matching typed text back to a place, so a saved profile reopens with its codes.
export function findByName<T extends Place>(places: T[], name: string | null | undefined) {
  const wanted = name?.trim().toLowerCase();
  return wanted ? places.find((p) => p.name.toLowerCase() === wanted) : undefined;
}
